# This file configures the deployment of your app on Render.
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: skillswap
    env: node
    plan: free # Change to a paid plan for production apps
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm start'
    envVars:
      # This is where you will add your Firebase environment variables on the Render dashboard.
      # Create an Environment Group in Render and add the keys from your .env file.
      - fromGroup: skillswap-env
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
